FROM node:12.16-alpine

ENV HOME /root
WORKDIR /root


# install tini to properly handle zombie reaping & signal comm
RUN apk add --update --no-cache tini bash curl git

ENTRYPOINT ["/sbin/tini", "--"]

COPY package*.json ./

RUN npm install

COPY tsconfig.json babel.config.js vue.config.js .eslintrc.js ./

COPY ./src ./src

CMD ["npm","run", "serve"]